### ISSUE TITLE
Level 1 Puzzles

### ISSUE THREAD

**Issue by erokasyuart** [ChaseBENNC9/GameJam-Charika#39]
Implementing the puzzle mechanics into level 1
- [x] Collect ball for child &#8594; valve
- [x] Hidden pipe piece in bedroom &#8594; pipe piece
- [x] Drain cellar &#8594;  contains ladder
- [x] Place ladder and access attic &#8594; study/library key
- [x] Study/library &#8594; main door key
